tbdd/apps/dhead/urls.py
from django.conf.urls.defaults import *


urlpatterns = patterns('tbdd.apps.dhead.views',
    url(regex=  r'^$',
        view=   'productlist',
        name=   'dhead_productlist',
    ),
    url(regex=  r'^about/$',
        view=   'about',
        name=   'dhead_about',
    ),
    url(regex=  r'^privacy/$',
        view=   'privacy',
        name=   'dhead_privacy',
    ),
    url(regex=  r'^(?P<keywords>[\w-]+)/$',
        view=   'productlist',
        name=   'dhead_productlist',
    ),
    url(regex=  r'^(?P<keywords>[\w-]+)/(?P<page>[\d]+)/$',
        view=   'productlist',
        name=   'dhead_productlist',
    ),
    url(regex=  r'^(?P<keywords>[\w-]+)/(?P<title_slug>[\w-]+)-(?P<asin>[\w]+)/$',
        view=   'productdetail',
        name=   'dhead_productdetail',
    ),
    url(regex=  r'^go/(?P<asin>[\w]+)/$',
        view=   'productgo',
        name=   'dhead_productgo',
    ),
)

tbdd/configs/common/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    url(regex=  r'^admin/doc/',
        view=   include('django.contrib.admindocs.urls'),
    ),
    url(regex=  r'^admin/',
        view=   include(admin.site.urls),
    ),
    url(regex=  r'^assets/(?P<path>.*)$',
        view=   'django.views.static.serve',
        kwargs= dict(
            document_root=settings.MEDIA_ROOT,
        ),
    ),
    url(regex=  r'',
        view=   include('tbdd.apps.dhead.urls'),
    ),
)

tbdd/apps/dhead/models.py
from django.contrib.sites.models import Site
from django.db import models

# Create your models here.


AMAZON_ZONE_CHOICES = (
    ('com', 'United States (com)'),
    ('co.uk', 'United Kingdom (co.uk)'),
    ('de', 'Germany (de)'),
    ('fr', 'France (fr)'),
    ('co.jp', 'Japan (co.jp)'),
    ('ca', 'Canada (ca)'),
)


class Storefront(models.Model):

    site = models.OneToOneField(Site)
    amazon_zone = models.CharField(max_length=10, choices=AMAZON_ZONE_CHOICES)
    amazon_category = models.CharField(max_length=100)
    associate_tag = models.CharField(max_length=100, default='')
    primary_keywords = models.CharField(max_length=255)
    alternate_keywords = models.CharField(max_length=255)
    analytics_footer = models.TextField(blank=True)

    class Meta:
        pass

    def __unicode__(self):
        return u"Storefront for {0}".format(self.site)


class Category(models.Model):

    storefront = models.ForeignKey(Storefront)
    weight = models.IntegerField(default=0)
    title = models.CharField(max_length=100)
    keywords = models.CharField(max_length=255)

    class Meta:
        ordering = ('-weight', 'title')
        verbose_name_plural = u'Categories'

    def __unicode__(self):
        return u"Category {0}".format(self.title, self.storefront)

tbdd/apps/dhead/views.py
from json import loads
from xml.etree.ElementTree import fromstring

import bottlenose
from django.conf import settings
from django.contrib.sites.models import get_current_site
from django.http import HttpResponseNotFound
from django.shortcuts import get_object_or_404, render_to_response
from django.template.context import RequestContext

from tbdd.apps.dhead import cached
from tbdd.apps.dhead.lib import deslugify
from tbdd.apps.dhead.models import Storefront
from tbdd.lib.awsecs import ECS_TAG


def with_request_storefront(fn):
    def wrapped(request, *args, **kwargs):
        site = get_current_site(request)
        if 'storefront' not in kwargs:
            try:
                kwargs['storefront'] = Storefront.objects.get(site=site)
            except Storefront.DoesNotExist:
                kwargs['storefront'] = None
        if kwargs.get('storefront') is not None:
            return fn(request, *args, **kwargs)
        else:
            return HttpResponseNotFound()
    return wrapped


@with_request_storefront
def productdetail(request, keywords=None, title_slug=None, asin=None, template_name="dhead/itemdetail.html", extra_context=None, storefront=None, *args, **kwargs):
    extra_context = extra_context or {}
    keywords = deslugify(keywords)
    item = cached.amazon_lookup(storefront, asin)
    template_context = dict(
        extra_context,
        asin=asin,
        item=item,
        keywords=keywords,
        title_slug=title_slug,
        storefront=storefront,
    )
    return render_to_response(template_name, template_context, RequestContext(request))


@with_request_storefront
def productgo(request, asin=None, extra_context=None, storefront=None, *args, **kwargs):
    pass


@with_request_storefront
def productlist(request, keywords=None, page=1, template_name="dhead/itemlist.html", extra_context=None, storefront=None, *args, **kwargs):
    extra_context = extra_context or {}
    keywords = deslugify(keywords)
    page = int(page)
    # Build search term.
    if keywords is None:
        # Use primary keywords as default search.
        keywords = storefront.primary_keywords
    else:
        # Use search terms in URL if specified.
        keywords = keywords.replace('-', ' ')
    asin_list = cached.amazon_search(storefront, keywords, page)
    item_list = [cached.amazon_lookup(storefront, asin) for asin in asin_list]
    total_pages = cached.amazon_search_pages(storefront, keywords)
    if total_pages is None:
        pages = []
    else:
        pages = range(1, total_pages + 1)
    template_context = dict(
        extra_context,
        keywords=keywords,
        item_list=item_list,
        pages=pages,
        storefront=storefront,
    )
    return render_to_response(template_name, template_context, RequestContext(request))


@with_request_storefront
def about(request, template_name="dhead/about.html", extra_context=None, storefront=None, *args, **kwargs):
    extra_context = extra_context or {}
    template_context = dict(
        extra_context,
        storefront=storefront,
    )
    return render_to_response(template_name, template_context, RequestContext(request))


@with_request_storefront
def privacy(request, template_name="dhead/privacy.html", extra_context=None, storefront=None, *args, **kwargs):
    extra_context = extra_context or {}
    template_context = dict(
        extra_context,
        storefront=storefront,
    )
    return render_to_response(template_name, template_context, RequestContext(request))

tbdd/templates/base.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="/assets/css/reset.css" type="text/css" charset="utf-8"/>
    <link rel="stylesheet" href="/assets/css/base.css" type="text/css" charset="utf-8"/>
    {% block extrahead %}{% endblock %}
</head>
<body>
{% block body %}{% endblock %}
</body>
</html>

tbdd/templates/dhead/about.html
{% extends "dhead/base.html" %}
{% load i18n %}

{% block content %}
    <h1>About</h1>

    <p>
        {% blocktrans with storefront.site.domain as domain and storefront.primary_keywords as primary_keywords and storefront.alternate_keywords as alternate_keywords %}
            {{ domain }} is a one-stop online {{ alternate_keywords }}
            store where you can find the best {{ primary_keywords }}
            deals and offers.
        {% endblocktrans %}
    </p>

    <p>
        {% blocktrans with storefront.site.domain as domain and storefront.primary_keywords as primary_keywords and storefront.alternate_keywords as alternate_keywords %}
            We have discount, bargain, and wholesale offers for a wide variety of
            <em>{{ primary_keywords }}</em> brands.
            Feel free to search our {{ alternate_keywords }} products and read
            customer reviews.
        {% endblocktrans %}
    </p>

    <p>
        {% blocktrans with storefront.site.domain as domain %}
            You can contact us at admin@{{ domain }}.
        {% endblocktrans %}
    </p>
{% endblock %}

tbdd/templates/dhead/base.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{{ storefront.site.name }}{% endblock %}

{% block body %}
    <div id="header">
        <h1><a href="{% url dhead_productlist %}">{{ storefront.site.name }}</a></h1>

        <p id="tagline">
            {% blocktrans with storefront.primary_keywords as primary_keywords %}
                Shop for the best {{ primary_keywords }} offers and deals
            {% endblocktrans %}
        </p>

        <p id="welcome">
            {% blocktrans with storefront.primary_keywords as primary_keywords and storefront.alternate_keywords as alternate_keywords %}
                Welcome to the <strong>{{ primary_keywords }}</strong> Online Shop.
                Get your bargain <strong>{{ primary_keywords }}</strong> deals here.
                We have the best <em>{{ alternate_keywords }}</em> product offers.
            {% endblocktrans %}
        </p>
    </div>

    <div id="main">
        <div id="content">
            {% block content %}
            {% endblock %}
        </div>

        <div id="sidebar-left">
            <div id="categories">
                <h2>Categories</h2>

                <ul>
                    {% for category in storefront.category_set.all %}
                        {% with category.keywords|slugify as keywords %}
                            <li><a href="{% url dhead_productlist keywords=keywords %}">{{ category.title }}</a></li>
                        {% endwith %}
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>

    <div class="clear"></div>

    <div id="footer">
        <p>
            {% blocktrans with storefront.site.domain as domain and storefront.primary_keywords as primary_keywords and storefront.alternate_keywords as alternate_keywords %}
                <strong>{{ domain }}</strong> is the one-stop shop to find the best
                {{ primary_keywords }} deals and offers.

                We have discount, cheap, and wholesale offers for a wide variety of
                {{ primary_keywords }} brands.

                Feel free to browse our {{ alternate_keywords }} products.
            {% endblocktrans %}
        </p>

        <p>
            <a href="{% url dhead_about %}">{% trans "About" %}</a>
            |
            <a href="{% url dhead_privacy %}">{% trans "Privacy" %}</a>
        </p>
    </div>

    {{ storefront.analytics_footer|safe }}
{% endblock %}

tbdd/templates/dhead/itemdetail.html
{% extends "dhead/base.html" %}
{% load dhead_tags %}

{% block title %}{% with item|azitemattributes as attributes %}{{ attributes|aztitleattribute }}{% endwith %} - {{ block.super }}{% endblock %}

{% block content %}
    <div class="detail item">
        {% with item|azitemattributes as attributes %}
            {% with item|azasin as asin %}
            {% with attributes|aztitleattribute|slugify as title_slug %}
            {% with keywords|slugify as keywords %}
                {# {% url dhead_productdetail keywords=keywords,title_slug=title_slug,asin=asin as detail_url %} #}

                <h1 class="title">{{ attributes|aztitleattribute }}</h1>
                <div class="price">
                    {{ item|azformattedprice }}
                    &bull;
                    <a href="{{ item|azdetailpageurl }}">Buy</a>
                </div>
                <div class="detail">
                    {% with item|azproductdescription as description %}
                        {% if description %}
                            <div class="description">{{ description }}</div>
                        {% endif %}
                    {% endwith %}
                    {% with item|azlargeimage as image %}
                        {% if image %}
                            <div class="image"><img src="{{ image.url }}" width="{{ image.width }}" height="{{ image.height }}"></div>
                        {% endif %}
                    {% endwith %}
                    {% with attributes|azfeatureattributes as features %}
                        {% if features %}
                            <p><strong>Features include the following:</strong></p>
                            <ul>
                                {% for feature in features %}
                                    <li>{{ feature }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}
                    {% endwith %}

                    <p style="text-align:center;">
                        Price: <strong>{{ item|azformattedprice }}</strong>
                        <br>
                        <a href="{{ item|azdetailpageurl }}"><img src="/assets/images/buy_az.gif" width="90" height="28" alt="Buy from amazon.com"></a>
                    </p>
                </div>
                <div class="clear"></div>
            {% endwith %}
            {% endwith %}
            {% endwith %}
        {% endwith %}
    </div>
{% endblock %}

tbdd/templates/dhead/itemlist.html
{% extends "dhead/base.html" %}

{% block title %}{{ keywords|title }} - {{ block.super }}{% endblock %}

{% block content %}
    {% for item in item_list %}
        {% include "dhead/itemlist_detail.html" %}
    {% endfor %}

    <p style="text-align:center;">
        {% for page in pages %}
            {% with keywords|slugify as keywords %}
                {% if page == 1 %}
                    <a href="{% url dhead_productlist keywords=keywords %}">1</a>
                {% else %}
                    <a href="{% url dhead_productlist keywords=keywords page=page %}">{{ page }}</a>
                {% endif %}
            {% endwith %}
            {% if not forloop.last %}
                &bull;
            {% endif %}
        {% endfor %}
    </p>
{% endblock %}

tbdd/templates/dhead/itemlist_detail.html
{% load dhead_tags %}

<div class="list item">
    {% with item|azitemattributes as attributes %}
        {% with item|azasin as asin %}
        {% with attributes|aztitleattribute|slugify as title_slug %}
        {% with keywords|slugify as keywords %}
            {% url dhead_productdetail keywords=keywords,title_slug=title_slug,asin=asin as detail_url %}

            <h3 class="title"><a href="{{ detail_url }}">{{ attributes|aztitleattribute }}</a></h3>
            <div class="price">
                <a href="{{ detail_url }}">{{ item|azformattedprice }}</a>
            </div>
            {% with item|azmediumimage as image %}
                {% if image %}
                    <div class="floating image"><a href="{{ detail_url }}"><img src="{{ image.url }}" width="{{ image.width }}" height="{{ image.height }}"></a></div>
                {% endif %}
            {% endwith %}
            <div class="indented detail">
                {% with item|azproductdescription as description %}
                    {% if description %}
                        <div class="description">{{ description }}</div>
                    {% endif %}
                {% endwith %}
                {% with attributes|azfeatureattributes as features %}
                    {% if features %}
                        <ul>
                            {% for feature in features %}
                                <li>{{ feature }}</li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                {% endwith %}
            </div>
            <div class="clear"></div>
        {% endwith %}
        {% endwith %}
        {% endwith %}
    {% endwith %}
</div>

tbdd/templates/dhead/privacy.html
{% extends "dhead/base.html" %}
{% load i18n %}

{% block content %}

    <h1>Privacy Policy</h1>

    <p>
        {% blocktrans with storefront.site.domain as domain %}
            {{ domain }} takes your privacy seriously. This privacy policy describes what personal information we collect and how we use it.
        {% endblocktrans %}
    </p>

    <p>
        {% blocktrans %}
            <strong>Routine Information Collection</strong>
            <br>
            All web servers track basic information about their visitors. This information includes, but is not limited to, IP addresses, browser details, timestamps and referring pages. None of this information can personally identify specific visitors to this site. The information is tracked for routine administration and maintenance purposes.
        {% endblocktrans %}
    </p>

    <p>
        {% blocktrans %}
            <strong>Cookies and Web Beacons</strong>
            <br>
            Where necessary, Battery Ext uses cookies to store information about a visitor's preferences and history in order to better serve the visitor and/or present the visitor with customized content.
            <br>
            Advertising partners and other third parties may also use cookies, scripts and/or web beacons to track visitors to our site in order to display advertisements and other useful information. Such tracking is done directly by the third parties through their own servers and is subject to their own privacy policies.
        {% endblocktrans %}
    </p>

    <p>
        {% blocktrans %}
            <strong>Controlling Your Privacy</strong>
            <br>
            Note that you can change your browser settings to disable cookies if you have privacy concerns. Disabling cookies for all sites is not recommended as it may interfere with your use of some sites. The best option is to disable or enable cookies on a per-site basis. Consult your browser documentation for instructions on how to block cookies and other tracking mechanisms.
        {% endblocktrans %}
    </p>

    <p>
        {% blocktrans %}
            <strong>DoubleClick DART cookies</strong>
            <br>
            We also may use DART cookies for ad serving through Google's DoubleClick, which places a cookie on your computer when you are browsing the web and visit a site using DoubleClick advertising (including some Google AdSense advertisements). This cookie is used to serve ads specific to you and your interests ("interest based targeting"). The ads served will be targeted based on your previous browsing history (For example, if you have been viewing sites about visiting Las Vegas, you may see Las Vegas hotel advertisements when viewing a non-related site, such as on a site about hockey). DART uses "non personally identifiable information". It does NOT track personal information about you, such as your name, email address, physical address, telephone number, social security numbers, bank account numbers or credit card numbers. You can opt-out of this ad serving on all sites using this advertising by visiting http://www.doubleclick.com/privacy/dart_adserving.aspx
        {% endblocktrans %}
    </p>

    <p>
        {% blocktrans with storefront.site.domain as domain %}
            <strong>Contact Information</strong>
            <br>
            Concerns or questions about this privacy policy can be directed to admin@{{ domain }} for further clarification.
        {% endblocktrans %}
    </p>

{% endblock %}